
    
tdmq:
  tunnel: 
    url: 172.28.1.44:6000
    netModel: pulsar-wzjazvkdgk/vpc-8fqcmjjh/subnet-5d6jpqtu
    secret: eyJrZXlJZCI6InB1bHNhci13emphenZrZGdrIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJwcm9kIn0.X4LJG_sUmaWgnSBDvLAI7BYhHbS6deqoo2sqz4UT2Vc
  topic:
    send: pulsar-wzjazvkdgk/prod/MessageCenterSend
    