
spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
    dynamic:
      druid:
        initial-size: 1
        max-active: 100
        min-idle: 0
        max-wait: 60000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        filters: stat,slf4j
      datasource:
        master:
          url: jdbc:mysql://172.29.3.3:3306/developer?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
          username: developer
          password: developer123
  redis: 
    database: 15
    host: 172.29.3.9
    port: 36379
    password: redis@gzmpc
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 1000ms
    