
tsf:
  swagger: 
    enabled: false

# redis
spring: 
  redis: 
    database: 15
    host: 172.28.2.16
    port: 36379
    password: redis@gzmpc
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 1000ms
  rabbitmq: 
    host: 172.28.2.15
    port: 5672
    username: gzmpc
    password: rabbit@gzmpc