
spring:
  data:
    mongodb: 
      uri: mongodb://config:config1015@172.29.3.13:27017/config?authSource=admin&readPreference=secondaryPreferred
  redis: 
   database: 15
   host: 172.29.3.9
   port: 36379
   password: redis@gzmpc
   pool:
     max-active: 200
     max-wait: -1
     max-idle: 10
     min-idle: 0
   timeout: 1000ms