server:
  port: 80
    
logging:
    file: /gzmpc-cloud-logs/${spring.application.name}/root.log
    level:
        root: INFO
spring:
    application:
        name: "@artifactId@"
    profiles:
        active: "@profile.active@"
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    cloud:
      bus:
        destination: GatewayBus
    ldap:
      #urls: auth.gzmpc.com
      urls: ldap://192.168.7.30:389
      base: dc=gzmpc,dc=com
      username: "uid=admin,ou=system"
      password: gzmpcldap
    
        
tsf:
    swagger: 
        enabled: true
        basePackage: com.gzmpc.microservice.config.controller
        
feign: 
  hystrix: 
    enabled: true

actable:
  table:
    auto: update
         #create    系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
         #update    系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。
         #none      系统不做任何处理。
         #add       新增表/新增字段/新增索引/新增唯一约束的功能，不做做修改和删除 (只在版本1.0.9.RELEASE及以上支持)。
  model:
    pack: com.gzmpc.portal.jdbc.entity,com.gzmpc.business.developer.portal.entity #扫描用于创建表的对象的包名，多个包用“,”隔开
  database:
    type: mysql #数据库类型 目前只支持mysqll
    
mybatis-plus:
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  
#exframework: 
#  config: 
#    enable: true